version: '3.8'

services:
  web:
    image: my-django-app
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
